#!/usr/bin/python           # This is server.py file

import socket               # Import socket module

s = socket.socket()         # Create a socket object
host = '192.168.43.99'        # Get local machine name
port = 5000            # Reserve a port for your service.


s.connect((host,port))
print s.recv(1024)
s.close
