#!/usr/bin/python           # This is server.py file

import socket   # Import socket module
import time

s = socket.socket()         # Create a socket object
host = '192.168.43.99'        # Get local machine name
port = 5000               # Reserve a port for your service.
s.bind((host, port))        # Bind to the port

s.listen(5)         # Now wait for client connection.
x=1
while True:
   x=x+1
   c, addr = s.accept()     # Establish connection with client.
   print 'Got connection from', addr
   c.send('thank you')
   while True:
       print c.recv(1024)
   
   #c.close()   
